- id: '1721661135970'
  alias: Presence Lighting
  description: Lighting automated by presence
  trigger:
  - platform: state
    entity_id:
    - input_boolean.presence
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.adaptive_lighting_presence
  mode: single
- id: '1723017555659'
  alias: Tap/Dial Switch
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.adaptive_lighting_presence
    to: 'on'
  condition: []
  action:
  - alias: Front Foyer Tap/Dial Switch
    if:
    - condition: state
      entity_id: event.button_front_foyer_1
      attribute: event_type
      state: short_release
    then:
    - metadata: {}
      data: {}
      target:
        entity_id:
        - light.lights_external_garage
      action: light.toggle
    else:
    - alias: Front Foyer Button 2 is Short-pressed
      if:
      - condition: state
        entity_id: event.button_front_foyer_2
        attribute: event_type
        state: short_release
      then:
      - metadata: {}
        data: {}
        target:
          entity_id:
          - light.downlights_external_porch
        action: light.toggle
    - alias: Front Foyer Button 3 is Short-pressed
      if:
      - condition: state
        entity_id: event.button_front_foyer_3
        attribute: event_type
        state: short_release
      then:
      - metadata: {}
        data: {}
        target:
          entity_id:
          - light.downlights_internal_lounge_room
        action: light.toggle
    - alias: Front Foyer Button 4 is Short-pressed
      if:
      - condition: state
        entity_id: event.button_front_foyer_4
        attribute: event_type
        state: short_release
      then:
      - metadata: {}
        data: {}
        target:
          entity_id:
          - light.downlights_internal_foyer_front
        action: light.toggle
    - alias: Front Foyer Dial is turned clockwise
      if:
      - condition: state
        entity_id: event.rotary_front_foyer
        attribute: event_type
        state: clock_wise
      then:
      - metadata: {}
        data:
          brightness_step_pct: 1
          brightness_pct: 1
        target:
          entity_id: light.downlights_internal_lounge_room
        action: light.turn_on
      else:
      - if:
        - condition: state
          entity_id: event.rotary_front_foyer
          attribute: event_type
          state: counter_clock_wise
        then:
        - target:
            entity_id:
            - light.downlights_internal_lounge_room
          data:
            brightness_step_pct: -1
          action: light.turn_on
  - if:
    - condition: state
      entity_id: input_boolean.presence
      state: 'off'
    then:
    - alias: Front Foyer Tap/Dial Switch
      if:
      - condition: state
        entity_id: event.button_front_foyer_1
        attribute: event_type
        state: short_release
      then:
      - metadata: {}
        data: {}
        target:
          entity_id: light.battens_external_garage
        action: light.toggle
      else:
      - alias: Front Foyer Button 2 is Short-pressed
        if:
        - condition: state
          entity_id: event.button_front_foyer_2
          attribute: event_type
          state: short_release
        then:
        - metadata: {}
          data: {}
          target:
            entity_id: light.downlights_external_porch
          action: light.toggle
      - alias: Front Foyer Button 3 is Short-pressed
        if:
        - condition: state
          entity_id: event.button_front_foyer_3
          attribute: event_type
          state: short_release
        then:
        - metadata: {}
          data: {}
          target:
            entity_id:
            - light.downlights_internal_lounge_room
          action: light.toggle
      - alias: Front Foyer Button 4 is Short-pressed
        if:
        - condition: state
          entity_id: event.button_front_foyer_4
          attribute: event_type
          state: short_release
        then:
        - metadata: {}
          data: {}
          target:
            entity_id:
            - light.downlights_internal_foyer_front
          action: light.toggle
  mode: single
