- id: '1720236172840'
  alias: Presence Lighting
  description: Lighting automated by presence
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.home_nearest_distance
    id: Approaching
    below: 10
  - platform: numeric_state
    entity_id:
    - zone.home
    above: 0
    id: Approaching
  - platform: state
    entity_id:
    - zone.home
    to: '0'
    id: Leaving
  - platform: numeric_state
    entity_id:
    - sensor.home_nearest_distance
    above: 10
    id: Leaving
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: trigger
          id:
          - Approaching
        - condition: or
          conditions:
          - condition: state
            entity_id: sensor.home_nearest_direction_of_travel
            state: towards
          - condition: state
            entity_id: sensor.home_nearest_direction_of_travel
            state: arrived
      sequence:
      - service: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.presence
    - conditions:
      - condition: trigger
        id:
        - Approaching
      sequence:
      - service: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
          - input_boolean.presence
          - input_boolean.adaptive_lighting_presence
      - service: adaptive_lighting.change_switch_settings
        metadata: {}
        data:
          use_defaults: configuration
          entity_id: switch.adaptive_lighting
    - conditions:
      - condition: trigger
        id:
        - Leaving
      sequence:
      - service: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - input_boolean.presence
          - input_boolean.adaptive_lighting_presence
      - service: adaptive_lighting.change_switch_settings
        metadata: {}
        data:
          use_defaults: configuration
          entity_id: switch.adaptive_lighting
          max_brightness: '25'
          min_brightness: '1'
  mode: single
- id: '1721558556926'
  alias: Tap/Dial Switch
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.presence
    to: 'on'
  condition: []
  action:
  - alias: Front Foyer Tap/Dial Switch
    if:
    - condition: state
      entity_id: event.button_front_foyer_1
      attribute: event_type
      state: short_release
    then:
    - service: light.toggle
      metadata: {}
      data: {}
      target:
        entity_id: light.lights_garage
    else:
    - if:
      - condition: state
        entity_id: event.button_front_foyer_2
        attribute: event_type
        state: short_release
      then:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.lights_porch_front
      alias: Front Foyer Button 2 is Short-pressed
    - alias: Front Foyer Button 3 is Short-pressed
      if:
      - condition: state
        entity_id: event.button_front_foyer_3
        attribute: event_type
        state: short_release
      then:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.downlights_lounge_room
    - alias: Front Foyer Button 4 is Short-pressed
      if:
      - condition: state
        entity_id: event.button_front_foyer_4
        attribute: event_type
        state: short_release
      then:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.lights_foyer_front
    - alias: Front Foyer Dial is turned clockwise
      if:
      - condition: state
        entity_id: event.rotary_front_foyer
        attribute: event_type
        state: clock_wise
      then:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 1
          brightness_pct: 1
        target:
          entity_id: light.downlights_lounge_room
  mode: single
