###############################################################################
#   @author         :   SchmittyD
#   @created date   :   16/07/2024 (AEST)
#   @edited date    :   18/07/2024 (AEST)
#   @package        :   Lighting
#   @description    :   Lighting automations
###############################################################################

automation:
## Presence ##
  - id: '2087207569523'
    alias: Presence Lighting
    description: 'Lighting automated by presence'
    trigger:
    - platform: numeric_state
      entity_id:
      - sensor.home_nearest_distance
      id: Approaching
      below: 10
    - platform: numeric_state
      entity_id:
      - zone.home
      above: 0
      id: Approaching
    - platform: state
      entity_id:
      - zone.home
      to: '0'
      id: Leaving
    - platform: numeric_state
      entity_id:
      - sensor.home_nearest_distance
      above: 10
      id: Leaving
    condition: []
    action:
    - choose:
      - conditions:
        - condition: and
          conditions:
          - condition: trigger
            id:
            - Approaching
          - condition: or
            conditions:
            - condition: state
              entity_id: sensor.home_nearest_direction_of_travel
              state: towards
            - condition: state
              entity_id: sensor.home_nearest_direction_of_travel
              state: arrived
        sequence:
        - service: input_boolean.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: input_boolean.presence
      - conditions:
        - condition: trigger
          id:
          - Approaching
        sequence:
        - service: input_boolean.turn_on
          metadata: {}
          data: {}
          target:
            entity_id:
            - input_boolean.presence
            - input_boolean.adaptive_lighting_presence
        - service: adaptive_lighting.change_switch_settings
          metadata: {}
          data:
            use_defaults: configuration
            entity_id: switch.adaptive_lighting
      - conditions:
        - condition: trigger
          id:
          - Leaving
        sequence:
        - service: input_boolean.turn_off
          metadata: {}
          data: {}
          target:
            entity_id:
            - input_boolean.presence
            - input_boolean.adaptive_lighting_presence
        - service: adaptive_lighting.change_switch_settings
          metadata: {}
          data:
            use_defaults: configuration
            entity_id: switch.adaptive_lighting
            max_brightness: '25'
            min_brightness: '1'
    mode: single
## Night Mode ##
  - id: '3605516720550'
    alias: Night Mode Lighting
    description: 'Set certain lights to Night Mode'
    trigger:
      - platform: state
        entity_id:
          - scene.night
        to: null
    condition: []
    action:
      - service: adaptive_lighting.apply
        data:
          entity_id: switch.adaptive_lighting_night_sleep_mode
          lights:
            - light.lights_zone_night
      - service: adaptive_lighting.change_switch_settings
        data:
          use_defaults: configuration
          sleep_rgb_color:
            - 1
            - 0
            - 138
    mode: single
