###############################################################################
#   @author         :   SchmittyD
#   @created date   :   16/07/2024 (AEST)
#   @edited date    :   18/07/2024 (AEST)
#   @package        :   Lighting
#   @description    :   Lighting automations
###############################################################################

automation:
## Presence ##
  - id: '2087207569523'
    alias: Presence Lighting
    description: Lighting automated by presence
    trigger:
      - platform: state
        entity_id:
          - input_boolean.presence
        to: "on"
    condition: []
    action:
      - service: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.adaptive_lighting_presence
    mode: single
## Night Mode ##
  - id: '3605516720550'
    alias: Night Mode Lighting
    description: 'Set certain lights to Night Mode'
    trigger:
      - platform: state
        entity_id:
          - scene.night
        to: null
    condition: []
    action:
      - service: adaptive_lighting.apply
        data:
          entity_id: switch.adaptive_lighting_night_sleep_mode
          lights:
            - light.lights_zone_night
      - service: adaptive_lighting.change_switch_settings
        data:
          use_defaults: configuration
          sleep_rgb_color:
            - 1
            - 0
            - 138
    mode: single
